# Generated by Django 5.2.5 on 2025-08-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_remove_user_unique_user_email_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("name", models.CharField(max_length=150)),
                ("color", models.CharField(default="", max_length=32)),
                ("x", models.FloatField(default=0.5)),
                ("y", models.FloatField(default=0.5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "updated_at"],
                        name="community_p_project_e3f117_idx",
                    )
                ],
                "unique_together": {("project", "user_id")},
            },
        ),
    ]
